plugins {
    id 'com.android.library'
    alias(libs.plugins.kotlin.android)
}

android {
    compileSdk libs.versions.compileSdk.get().toInteger()
    namespace 'ru.orangesoftware.financisto.core.common'
    
    defaultConfig {
        minSdkVersion libs.versions.minSdk.get().toInteger()
        targetSdkVersion libs.versions.targetSdk.get().toInteger()
        
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation libs.bundles.kotlin
    
    // Testing
    testImplementation libs.junit
}
