plugins {
    id 'com.android.library'
    alias(libs.plugins.kotlin.android)
    id 'kotlin-kapt'
    alias(libs.plugins.hilt.android)
    id 'kotlin-parcelize'
}

android {
    compileSdk libs.versions.compileSdk.get().toInteger()
    namespace 'ru.orangesoftware.financisto.feature.blotter'
    
    defaultConfig {
        minSdkVersion libs.versions.minSdk.get().toInteger()
        targetSdkVersion libs.versions.targetSdk.get().toInteger()
        
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    
    kotlinOptions {
        jvmTarget = '17'
    }
    
    buildFeatures {
        compose true
    }
    
    composeOptions {
        kotlinCompilerExtensionVersion = libs.versions.composeCompiler.get()
    }
}

dependencies {
    implementation project(':core:common')
    implementation project(':core:ui')
    implementation project(':usecase')
    implementation project(':repository')
    
    implementation libs.bundles.kotlin
    implementation libs.androidx.core.ktx
    implementation libs.androidx.activity.ktx
    implementation libs.material
    implementation libs.bundles.lifecycle
    
    // Compose
    implementation platform(libs.compose.bom)
    implementation libs.bundles.compose
    implementation libs.compose.ui.tooling
    implementation libs.compose.navigation
    implementation libs.compose.hilt.navigation
    
    // Dependency Injection
    implementation libs.bundles.hilt
    kapt libs.hilt.compiler
    
    // Coroutines
    implementation libs.bundles.coroutines
    
    // Testing
    testImplementation libs.junit
    testImplementation libs.bundles.testing
    
    androidTestImplementation libs.androidx.test.core
    androidTestImplementation libs.hilt.android.testing
    kaptAndroidTest libs.hilt.compiler
}
